[project]
name = "kdl2html"
version = "0.1.0"
description = "A PoC KDL to HTML converter"
requires-python = ">=3.13"
dependencies = [
    "cuddle",
    "htpy",
]

[project.scripts]
kdl2html = "kdl2html.__main__:main"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
